---

- hosts: localhost
  gather_facts: yes
  tasks:
  - include_role:
        name: openshift
  - include_role:
        name: 3scale_router_validation
  - include_role:
        name: fuse_dashboard_syndesis_integration
  - include_role:
        name: update_runtime_image_streams